#!/usr/bin/env python3
"""Generate .ai/cockpit/current_status.md from a Contract and Summary."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ai_common import PROJECT_ROOT, load_json
from ai_observability import DEFAULT_LOG_PATH, create_observability


DEFAULT_OUTPUT = PROJECT_ROOT / ".ai" / "cockpit" / "current_status.md"
BACKTRACK_REPORT = PROJECT_ROOT / "target" / "ai_backtrack_report.json"
DEFAULT_RETRY_THRESHOLD = 5


def consecutive_failure_count(work_item_id: str, log_path: Path = DEFAULT_LOG_PATH) -> int:
    if not work_item_id or not log_path.exists():
        return 0
    count = 0
    try:
        lines = log_path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return 0
    for raw in reversed(lines):
        try:
            event = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if not isinstance(event, dict) or event.get("workItemId") != work_item_id:
            continue
        if event.get("eventType") == "check_failed":
            count += 1
            continue
        if event.get("eventType") == "check_passed":
            break
    return count


def status_for(
    contract: dict[str, Any],
    summary: dict[str, Any] | None,
    *,
    retry_threshold: int,
    observability_log: Path,
) -> tuple[str, list[str]]:
    blockers: list[str] = []
    work_item_id = contract.get("workItemId", "")
    if isinstance(work_item_id, str) and retry_threshold > 0:
        failures = consecutive_failure_count(work_item_id, observability_log)
        if failures >= retry_threshold:
            return "blocked_by_ai_loop", [f"retry circuit breaker: consecutive check failures {failures}/{retry_threshold}"]

    if contract.get("notCodable") is True:
        blockers.append("notCodable: true")
    unknowns = contract.get("unknowns")
    if isinstance(unknowns, list) and unknowns:
        blockers.append(f"unknowns: {len(unknowns)}")
    if summary is None:
        blockers.append("summary is missing")
    else:
        status = {item.get("command"): item.get("result") for item in summary.get("verification", []) if isinstance(item, dict)}
        for item in contract.get("verification", []):
            if not isinstance(item, dict) or item.get("required") is not True:
                continue
            command = item.get("command")
            if status.get(command) != "passed":
                blockers.append(f"required check not passed: {command}")
    return ("blocked", blockers) if blockers else ("ready_for_review", [])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate AI Cockpit current status.")
    parser.add_argument("contract", nargs="?")
    parser.add_argument("--summary")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--observability-log", default=str(DEFAULT_LOG_PATH))
    parser.add_argument("--retry-threshold", type=int, default=DEFAULT_RETRY_THRESHOLD)
    parser.add_argument("--no-active", action="store_true", help="Generate a no-active-work-item status.")
    return parser.parse_args()


def write_no_active_status(output: Path) -> None:
    lines = [
        "---",
        "title: AI Cockpit Current Status",
        "generated: true",
        "---",
        "",
        "# AI Cockpit Current Status",
        "",
        "This file is generated by `scripts/ai_generate_status.py`. Do not update it by hand.",
        "",
        f"- Generated At: `{datetime.now(timezone.utc).isoformat()}`",
        "- Task: `none`",
        "- Mode: `none`",
        "- State: `no_active_work_item`",
        "- Contract Path: ``",
        "- Summary Path: ``",
        "",
        "## Blocking",
        "",
        "- none",
        "",
        "## Required Checks",
        "",
        "- none",
        "",
        "## Changed Files",
        "",
        "- none",
        "",
        "## Backtrack",
        "",
        "- Status: `not_run`",
        "",
        "## Next Action",
        "",
        "- create a Work Item with `make ai-start TASK=<task>`",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    output = Path(args.output)
    if args.no_active or not args.contract:
        write_no_active_status(output)
        print(f"cockpit status generated (no active Work Item): {output}")
        return 0
    try:
        contract = load_json(Path(args.contract))
        summary_path = Path(args.summary) if args.summary else None
        summary = load_json(summary_path) if summary_path and summary_path.exists() else None
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"Failed to generate Cockpit status: {exc}", file=sys.stderr)
        return 1

    state, blockers = status_for(
        contract,
        summary,
        retry_threshold=args.retry_threshold,
        observability_log=Path(args.observability_log),
    )
    backtrack = load_json(BACKTRACK_REPORT) if BACKTRACK_REPORT.exists() else None
    changed_files = summary.get("changedFiles", []) if isinstance(summary, dict) else []
    verification = summary.get("verification", []) if isinstance(summary, dict) else []

    lines = [
        "---",
        "title: AI Cockpit Current Status",
        "generated: true",
        "---",
        "",
        "# AI Cockpit Current Status",
        "",
        "This file is generated by `scripts/ai_generate_status.py`. Do not update it by hand.",
        "",
        f"- Generated At: `{datetime.now(timezone.utc).isoformat()}`",
        f"- Task: `{contract.get('workItemId', '')}`",
        f"- Mode: `{contract.get('mode', '')}`",
        f"- State: `{state}`",
        f"- Contract Path: `{args.contract}`",
        f"- Summary Path: `{args.summary or ''}`",
        "",
        "## Blocking",
        "",
    ]
    lines.extend([f"- {blocker}" for blocker in blockers] if blockers else ["- none"])
    lines.extend(["", "## Required Checks", ""])
    if verification:
        for item in verification:
            if isinstance(item, dict):
                lines.append(f"- `{item.get('command', '')}`: {item.get('result', '')}")
    else:
        lines.append("- none")

    lines.extend(["", "## Changed Files", ""])
    if changed_files:
        for item in changed_files:
            if isinstance(item, dict):
                lines.append(f"- `{item.get('path', '')}`: {item.get('reason', '')}")
    else:
        lines.append("- none")

    lines.extend(["", "## Backtrack", ""])
    if isinstance(backtrack, dict):
        lines.append(f"- Status: `{backtrack.get('status', 'unknown')}`")
        lines.append(f"- Report: `{BACKTRACK_REPORT.relative_to(PROJECT_ROOT)}`")
        items = backtrack.get("items", [])
        if isinstance(items, list) and items:
            for item in items:
                if isinstance(item, dict):
                    lines.append(f"- {item.get('kind')}: `{item.get('path')}` - {item.get('detail')}")
        else:
            lines.append("- Items: none")
    else:
        lines.append("- Status: `not_run`")

    lines.extend(["", "## Next Action", "", "- human review / commit decision"])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"cockpit status generated: {output}")

    create_observability(work_item_id=contract.get("workItemId", "")).status_generated(
        state=state,
        output_path=str(output.relative_to(PROJECT_ROOT)),
        fields={"blockers": len(blockers), "changedFiles": len(changed_files)},
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())

